import type { AgentUsage } from "../claudeAgent.js";
import type { StageName, StageStatus } from "./types.js";

export interface TracingPackEntry {
  stage: StageName;
  status: StageStatus;
  input?: unknown;
  output?: unknown;
  usage?: AgentUsage;
}

function renderField(label: string, value: unknown): string {
  if (value === undefined) {
    return `**${label}**\n\n_none_`;
  }
  return `**${label}**\n\n\`\`\`json\n${JSON.stringify(value, null, 2)}\n\`\`\``;
}

function renderUsage(usage: AgentUsage): string {
  return [
    "**Tokens**",
    "",
    `input: ${usage.inputTokens}, output: ${usage.outputTokens}, ` +
      `cache read: ${usage.cacheReadInputTokens}, cache write: ${usage.cacheCreationInputTokens}, ` +
      `cost: $${usage.costUsd.toFixed(4)}`,
  ].join("\n");
}

function renderEntry(entry: TracingPackEntry): string {
  const parts = [
    `## ${entry.stage}`,
    "",
    `Status: \`${entry.status}\``,
    "",
    renderField("Input", entry.input),
    "",
    renderField("Output", entry.output),
  ];
  if (entry.usage) {
    parts.push("", renderUsage(entry.usage));
  }
  return parts.join("\n");
}

export function formatTracingPackMarkdown(entries: TracingPackEntry[], outcome: string): string {
  return [
    "# Tracing Pack",
    "",
    `Outcome: **${outcome}**`,
    "",
    "Generated by the idea-to-mvp pipeline. One section per stage, showing exactly what was read (Input) and produced (Output).",
    "",
    ...entries.map(renderEntry),
  ].join("\n\n");
}
